// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy_ZIn6gnVe_U0TSPr67B6W3-NA-YeXP4',
    appId: '1:872950012239:web:56ad33e4c2195092ac8d3a',
    messagingSenderId: '872950012239',
    projectId: 'tree-plantation-692f8',
    authDomain: 'tree-plantation-692f8.firebaseapp.com',
    storageBucket: 'tree-plantation-692f8.appspot.com',
    measurementId: 'G-N9ZPCS0WRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDgXa1SZorx8KgLZWmDOlCAx7Y0Y67jk',
    appId: '1:872950012239:android:591a2a8001934d98ac8d3a',
    messagingSenderId: '872950012239',
    projectId: 'tree-plantation-692f8',
    storageBucket: 'tree-plantation-692f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3VHZqjIZ2_mBFRWCRLdxZAl4MPg681JM',
    appId: '1:872950012239:ios:6887cf0a78b4f4a6ac8d3a',
    messagingSenderId: '872950012239',
    projectId: 'tree-plantation-692f8',
    storageBucket: 'tree-plantation-692f8.appspot.com',
    iosClientId: '872950012239-o3d4rm0hvhk02v671urrocafe7nhsi89.apps.googleusercontent.com',
    iosBundleId: 'com.rootless.treePlantationMob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3VHZqjIZ2_mBFRWCRLdxZAl4MPg681JM',
    appId: '1:872950012239:ios:6887cf0a78b4f4a6ac8d3a',
    messagingSenderId: '872950012239',
    projectId: 'tree-plantation-692f8',
    storageBucket: 'tree-plantation-692f8.appspot.com',
    iosClientId: '872950012239-o3d4rm0hvhk02v671urrocafe7nhsi89.apps.googleusercontent.com',
    iosBundleId: 'com.rootless.treePlantationMob',
  );
}
